[pytest]
minversion = 6.0
addopts = -ra -q --cov=app --cov-report=term-missing:skip-covered
testpaths =
    tests
markers =
    feature: Feature tests
    current: Run only tests that are currently being developed
    [pytest]
asyncio_mode = strict
