# Listing all the environments
TEST_ENVIRONMENT = "test"
LOCAL_ENVIRONMENT = "local"
DEVELOPMENT_ENVIRONMENT = "development"
TESTING_ENVIRONMENT = "testing"
PRODUCTION_ENVIRONMENT = "production"

# Groups of environments
KUBERNETES_ENVIRONMENTS = [DEVELOPMENT_ENVIRONMENT, TESTING_ENVIRONMENT, PRODUCTION_ENVIRONMENT]
LOCAL_ENVIRONMENTS = [LOCAL_ENVIRONMENT, TEST_ENVIRONMENT]
DEVTOOLS_ENVIRONMENTS = [LOCAL_ENVIRONMENT, TEST_ENVIRONMENT, DEVELOPMENT_ENVIRONMENT, TESTING_ENVIRONMENT]
